export const NotificationType = Object.freeze({
  PROFILE_NOTIFICATION: 'PROFILE_NOTIFICATION',
  MESSAGE_NOTIFICATION: 'MESSAGE_NOTIFICATION',
  PRICE_PLAN_NOTIFICATION: 'PRICE_PLAN_NOTIFICATION',
  EVENT_NOTIFICATION: 'EVENT_NOTIFICATION',
  INVITATION_NOTIFICATION: 'EVENT_INVITATION',
  BLOG_NOTIFICATION: 'BLOG_NOTIFICATION',
  LOGIN: 'LOGIN',
  LOGIN_ATTEMPT: 'LOGIN_ATTEMPT',
  MESSAGE_REQUEST: 'MESSAGE_REQUEST',
  PASSWORD_RESET:'PASSWORD_RESET',
  JOIN_EVENT:'JOIN_EVENT',
  CONNECT_USERS:'CONNECT_USERS'
});
